### ISSUE TITLE
Searchinng in Unimodeled arrays

### ISSUE THREAD

**Issue by ghost** [nvs-abhilash/FunctionLibrary#18]
#17

**Comment by ghost** [comment]
uni modelled arrays has to be a part of which funProgram / searchAlgorithms

**Comment by siddharthshashikar** [comment]
searching in uni model arrays added in funPrpblems folder please verify

**Comment by ghost** [comment]
searching in uni model arrays added , plz verify

**Comment by nvs-abhilash** [comment]
This issue was adressed in #17
