### ISSUE TITLE
No searching algorithms exists

### ISSUE THREAD

**Issue by nvs-abhilash** [nvs-abhilash/FunctionLibrary#5]
Make a new folder in algorithms named searchingAlgorithms, and add linear and binary search in it.

**Comment by ghost** [comment]
I would love to contribute in this section!

**Comment by mohit-raj** [comment]
@siddharthshashikar  Are you **Working** on it ?

**Comment by nvs-abhilash** [comment]
This issue was adressed in #17 , Closing
